CREATE TABLE tbl_user_display_config (
    id VARCHAR(36) NOT NULL COMMENT '主键ID',
    user_id VARCHAR(36) NOT NULL COMMENT '用户ID',
    data_source_id VARCHAR(36) NOT NULL COMMENT '数据源ID',
    table_name VARCHAR(64) NOT NULL COMMENT '表名',
    column_name VARCHAR(64) NOT NULL COMMENT '列名',
    display_name VARCHAR(64) COMMENT '显示名称',
    width INT COMMENT '列宽度',
    align VARCHAR(16) COMMENT '列对齐方式',
    fixed VARCHAR(16) COMMENT '列固定位置',
    visible BOOLEAN DEFAULT TRUE COMMENT '是否可见',
    display_order INT NOT NULL COMMENT '显示顺序',
    is_query_condition BOOLEAN DEFAULT FALSE COMMENT '是否为查询条件',
    is_required BOOLEAN DEFAULT FALSE COMMENT '查询条件是否必填',
    default_value VARCHAR(255) COMMENT '查询条件默认值',
    is_advanced_condition BOOLEAN DEFAULT FALSE COMMENT '是否为高级查询条件',
    mask_type VARCHAR(32) COMMENT '数据掩码类型',
    mask_config TEXT COMMENT '掩码配置(JSON)',
    use_frequency INT DEFAULT 0 COMMENT '使用频率',
    last_used_at BIGINT COMMENT '最后使用时间',
    nonce INT DEFAULT 0 COMMENT '乐观锁版本号',
    created_at BIGINT NOT NULL COMMENT '创建时间',
    created_by VARCHAR(36) NOT NULL COMMENT '创建人',
    modified_at BIGINT NOT NULL COMMENT '最后修改时间',
    modified_by VARCHAR(36) NOT NULL COMMENT '最后修改人',
    PRIMARY KEY (id),
    INDEX idx_user_datasource (user_id, data_source_id),
    INDEX idx_user_table (user_id, data_source_id, table_name),
    INDEX idx_frequency (user_id, data_source_id, use_frequency)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户显示配置表';