CREATE TABLE tbl_user_display_config (
    id VARCHAR(36) NOT NULL COMMENT '主键ID',
    user_id VARCHAR(36) NOT NULL COMMENT '用户ID',
    data_source_id VARCHAR(36) NOT NULL COMMENT '数据源ID',
    table_name VARCHAR(64) NOT NULL COMMENT '表名',
    column_name VARCHAR(64) NOT NULL COMMENT '列名',
    display_name VARCHAR(64) NOT NULL COMMENT '显示名称',
    width INT NOT NULL COMMENT '列宽度',
    align VARCHAR(16) NOT NULL COMMENT '列对齐方式',
    fixed VARCHAR(16) COMMENT '列固定方式',
    visible BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否显示',
    order_num INT NOT NULL COMMENT '排序号',
    sortable BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否可排序',
    searchable BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否可搜索',
    required BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否必填',
    mask_type VARCHAR(16) COMMENT '掩码类型',
    mask_config TEXT COMMENT '掩码配置',
    usage_count BIGINT NOT NULL DEFAULT 0 COMMENT '使用次数',
    last_used_at DATETIME COMMENT '最后使用时间',
    nonce INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    created_by VARCHAR(36) NOT NULL COMMENT '创建人',
    modified_at DATETIME NOT NULL COMMENT '最后修改时间',
    modified_by VARCHAR(36) NOT NULL COMMENT '最后修改人',
    PRIMARY KEY (id),
    UNIQUE KEY u_idx_user_config (user_id, data_source_id, table_name, column_name),
    KEY idx_user_id (user_id),
    KEY idx_data_source_id (data_source_id),
    KEY idx_table_name (table_name),
    KEY idx_usage_count (usage_count),
    KEY idx_last_used_at (last_used_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户显示配置表';